sudo: false
os:
  - linux
  - osx
services:
  - mongodb
language: node_js
node_js:
  - "6"
before_install:
  - touch .env
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mongodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p $HOME/data/db && touch $HOME/mongo.log; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mongod --fork --dbpath $HOME/data/db --logpath $HOME/mongo.log; fi
env:
  global:
    - GOOGLE_CLIENT_ID=test
    - GOOGLE_CLIENT_SECRET=test
    - BASE_URL=devbox.example.com
notifications:
    on_success: change # default: change
    on_failure: change # default: always