sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - "6"
before_install:
  - touch .env
env:
  global:
    - GOOGLE_CLIENT_ID=test
    - GOOGLE_CLIENT_SECRET=test
    - BASE_URL=devbox.example.com